In [ ]:
# %pip install torch
# %pip install CUDA
# %pip install scanpy==1.8.1
# %pip install rpy2
# %pip install torchvision
# %pip install opencv-python
# %pip install torchtoolbox
# %pip install pandas

In [ ]:
import pandas as pd
import os
from ConGI.utils import load_ST_file
path = 'D:\\Genomics\\A2\\dataset-1\\SpatialLIBID\\'
def form_meta(name, path='barcode_level_layer_map.tsv'):
    file_path = os.path.join(os.path.dirname(path), 'metadata.tsv')
    df = pd.read_csv(path, delimiter='\t')
    print(df.head())
    data = {
    'barcodes': [],
    'layer_guess': []
    }
    for i in range(len(df['AAACAACGAATAGTTC-1'])):
        if df['151507'][i] == int(name):
            data['barcodes'].append(df['AAACAACGAATAGTTC-1'][i])
            data['layer_guess'].append(df['L1'][i])
    
    df = pd.DataFrame(data)
    print(df.head())
    print(df.shape)
    df.to_csv(os.path.join(path,name,'metadata.tsv'), sep='\t', index=True)

def adjust_meta():
    df_meta = pd.read_csv('D:\\Genomics\\A2\\dataset-1\\SpatialLIBID\\151507\\metadata.tsv', delimiter='\t')
    path = 'D:\Genomics\A2\dataset-1\SpatialLIBID'
    name = '151507'
    adata = load_ST_file(os.path.join(path, name))
    data = {
    'barcodes': [],
    'layer_guess': []
    }

    barcodelist = df_meta['barcodes'].values.tolist()
    layerlist = df_meta['layer_guess'].values.tolist()

    for barcode in adata.obs.index:
        try:
            index = barcodelist.index(str(barcode))
            data['barcodes'].append(barcodelist[index])
            data['layer_guess'].append(layerlist[index])
        except:
            data['barcodes'].append(str(barcode))
            data['layer_guess'].append(str(-1))
    df = pd.DataFrame(data)
    df.to_csv('D:\\Genomics\\A2\\dataset-1\\SpatialLIBID\\151507\\metadata.tsv', sep='\t', index=False)


form_meta(name = '151507')
adjust_meta()


In [ ]:
# from ConGI.utils import load_ST_file
# path = 'D:\Genomics\A2\dataset-1\SpatialLIBID'
# name = '151507'
# adata = load_ST_file(os.path.join(path, name))
# df_meta = pd.read_csv(os.path.join(path, name, 'metadata.tsv'), sep='\t')
# label = pd.Categorical(df_meta['layer_guess']).codes

# data = {
#     'barcodes': [],
#     'layer_guess': []
#     }

# barcodelist = df_meta['barcodes'].values.tolist()
# layerlist = df_meta['layer_guess'].values.tolist()

# for barcode in adata.obs.index:
#     try:
#         index = barcodelist.index(str(barcode))
#         data['barcodes'].append(barcodelist[index])
#         data['layer_guess'].append(layerlist[index])
#     except:
#         data['barcodes'].append(str(barcode))
#         data['layer_guess'].append(str(-1))
# print(data.keys())
# print(data['barcodes'])
# print(data['layer_guess'])
# print(barcodelist)
# print(layerlist)

In [14]:
import numpy as np

def pad_image(image_matrix):
    # Get the dimensions of the original image matrix
    height, width = image_matrix.shape

    # Determine the desired dimensions for the padded image
    padded_height = height + 2  # Add 2 rows of zeros (one at the top and one at the bottom)
    padded_width = width + 2    # Add 2 columns of zeros (one on the left and one on the right)

    # Create a new matrix filled with zeros with the desired dimensions
    padded_image = np.zeros((padded_height, padded_width), dtype=image_matrix.dtype)

    # Copy the original image into the center of the padded matrix
    padded_image[1:-1, 1:-1] = image_matrix

    return padded_image

# Example usage:
original_image = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

padded_image = pad_image(original_image)
print(padded_image)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [ ]:
%pwd

In [13]:
from dataset import Dataset
trainset = Dataset(dataset='SpatialLIBD', path='D:\GenSomics\A2\dataset-1\SpatialLIBID', name='151507', gene_preprocess=gene_preprocess, n_genes=n_gene,
                   prob_mask=prob_mask, pct_mask=pct_mask, prob_noise=prob_noise, pct_noise=pct_noise, sigma_noise=sigma_noise,
                   prob_swap=prob_swap, pct_swap=pct_swap, img_size=img_size, train=True)

# dataset = Dataset.__init__(dataset = "SpatialLIBD", path = 'D:\Genomics\A2\dataset-1\SpatialLIBID', name = '151507')
# dataset = Dataset(dataset='SpatialLIBD', path='D:\GenSomics\A2\dataset-1\SpatialLIBID', name='151507')
print(dataset)

NameError: name 'gene_preprocess' is not defined

In [12]:
# dataset.__init__
# dataset.__init_subclass__
# dataset.__getstate__
# dataset.__annotations__
dataset.image

array([], shape=(4226, 0, 0, 3), dtype=uint8)

In [2]:
# dataset.__init__(dataset='SpatialLIBD', path='D:\Genomics\A2\dataset-1\SpatialLIBID', name='151507')
dataset.__getitem__(0)
print(dir(dataset))
print(dataset.label)
print(dataset.img_train_transform)
print(dataset.image)

['__add__', '__annotations__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_is_protocol', 'gene', 'gene_train_transform', 'image', 'img_test_transform', 'img_train_transform', 'label', 'n_clusters', 'n_pos', 'spatial', 'train']
[0 3 1 ... 7 6 1]
Compose(
    ToTensor()
    RandomHorizontalFlip(p=0.5)
    RandomVerticalFlip(p=0.5)
    RandomApply(
    p=0.8
    ColorJitter(brightness=(0.6, 1.4), contrast=(0.6, 1.4), saturation=(0.6, 1.4), hue=(-0.1, 0.1))
)
    RandomGrayscale(p=0.2)
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)
[]


In [3]:
print(dataset.image.shape)
print(dataset.label.shape)
# print(dataset.label)
print(dataset.image[1].shape)
print(dataset.image[1])
print(dataset.gene_train_transform.__dict__)
print(dataset.img_train_transform.__dict__)


(4226, 0, 0, 3)
(4226,)
(0, 0, 3)
[]
{'training': True, '_parameters': OrderedDict(), '_buffers': OrderedDict(), '_non_persistent_buffers_set': set(), '_backward_pre_hooks': OrderedDict(), '_backward_hooks': OrderedDict(), '_is_full_backward_hook': None, '_forward_hooks': OrderedDict(), '_forward_hooks_with_kwargs': OrderedDict(), '_forward_hooks_always_called': OrderedDict(), '_forward_pre_hooks': OrderedDict(), '_forward_pre_hooks_with_kwargs': OrderedDict(), '_state_dict_hooks': OrderedDict(), '_state_dict_pre_hooks': OrderedDict(), '_load_state_dict_pre_hooks': OrderedDict(), '_load_state_dict_post_hooks': OrderedDict(), '_modules': OrderedDict(), 'n_genes': 3000, 'prob_mask': 0.5, 'pct_mask': 0.2, 'prob_noise': 0.5, 'pct_noise': 0.8, 'sigma_noise': 0.5, 'prob_swap': 0.5, 'pct_swap': 0.1}
{'transforms': [<torchtoolbox.transform.transforms.Cutout object at 0x000001C835D8E6D0>, ToTensor(), RandomHorizontalFlip(p=0.5), RandomVerticalFlip(p=0.5), RandomApply(
    p=0.8
    ColorJitter(

In [5]:
print(dataset.spatial)

[[3276 2514]
 [9178 8520]
 [5133 2878]
 ...
 [4218 9703]
 [4017 7906]
 [5683 3359]]


In [ ]:
#what can i access from dataset
print(dataset.__dict__.keys())